from ml.models.song import Song


class Playlist:
    songs = []
    model = ''  # what model is this playlist generated by
    random = False

    def __init__(self, songs, model, random):
        self.songs = songs
        self.model = model
        self.random = random
